[build-system]
requires = ["hatchling>=1.20.0"]
build-backend = "hatchling.build"

[project]
name = "isaacus-haystack"
version = "0.3.0"
description = "Isaacus models for Haystack 2.x"
readme = "README.md"
license = { text = "Apache-2.0" }
requires-python = ">=3.10"
authors = [{ name = "Isaacus" }]
dependencies = [
  "haystack-ai>=2.14.0",
  "isaacus>=0.21.0",
  "requests>=2.31.0",
]

[project.urls]
Homepage = "https://github.com/isaacus-dev/isaacus-haystack"
Source = "https://github.com/isaacus-dev/isaacus-haystack"
Issues = "https://github.com/isaacus-dev/isaacus-haystack/issues"
Documentation = "https://docs.isaacus.com/capabilities/embedding"

[tool.hatch.build.targets.wheel]
packages = ["src/haystack_integrations"]

[tool.hatch.build.targets.wheel.force-include]
"src/haystack_integrations/py.typed" = "haystack_integrations/py.typed"

[tool.hatch.build.targets.sdist]
exclude = [
  "/tests",
  "/.github",
  "/**/__pycache__",
  "/.pytest_cache",
  "/.mypy_cache",
  "/build",
  "/dist"
]

[tool.hatch.envs.test]
dependencies = [
  "pytest",
  "haystack-ai>=2.14.0",
  "requests>=2.31.0"
]

[tool.hatch.envs.test.scripts]
all = "pytest -q"

[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "pytest-asyncio>=1.2.0",
]
